name:                imp-interpreter
version:             0.1.0.0
github:              "crvdgc/imp-interpreter"
license:             BSD3
author:              "Liu Yuxi"
maintainer:          "ubikium@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/crvdgc/imp-interpreter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  imp-interpret:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imp-interpreter
    - tasty >= 1.2.3 && < 1.3

tests:
  imp-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imp-interpreter
